### PR TITLE
Add Lspsaga Support

### PR DESCRIPTION
**Pull request by kborling**
This adds color scheme support for the [lspsaga](https://github.com/glepnir/lspsaga.nvim) plugin.

I've tested this with all the color presets (including 'Christmas'), and they all look great. I can provide additional screenshots if needed.

**Before:**
image
image

**After:**
image
image

**Plugin Reference:**
https://github.com/glepnir/lspsaga.nvim/

**Highlight Reference:**
https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/highlight.lua

### CODE REVIEW

**Comment by n1ghtmare** [comment]
The colors for the last screenshot look a bit off (different) to me? I dunno if it's my screen?

**Comment by kborling** [comment]
Hmm, I can try it in a different terminal with a different font. I'm on macOS, so it could be something like Night Shift changing the colors a bit. Either way, I'll give it a shot. Thanks!

**Comment by kborling** [comment]
I looked at the screenshots again and realize the issue. In the last screenshot, the floating terminal utilizes whatever color scheme you have set in your terminal emulator. In my case, I'm using the [Sequoia Monochrome](https://wezfurlong.org/wezterm/colorschemes/s/index.html?highlight=monochr#sequoia-monochrome) theme in Wezterm. The only thing that I was able to change for the floating terminal was the background color. Probably not the best screenshot to use.

**Comment by n1ghtmare** [comment]
Cool! That's fine then, it's looking good! Thanks for the PR, much appreciated!

**Pull request merged**
